### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by JohnTitor**
This is a draft for a contributing guide.
Especially, the pull request section isn't well documented.

### CODE REVIEW

**Comment by r3v2d0g** [comment]
@JohnTitor For now, people should join the (newly created) `#dev` channel on our discord (https://discordapp.com/invite/DqRqtRT) and we will help them get started.

We will write a guide later (maybe we need to help new contributors this way to know how to write the best guide possible) :smiley:

**Comment by JohnTitor** [comment]
Added our Discord server link

**Comment by vertexclique** [comment]
We can add unsafe guidelines here. Requested here:
https://www.reddit.com/r/rust/comments/dvtrrv/announcing_bastion_03_the_kraken_has_been_released/f7ha6ie/

**Comment by JohnTitor** [comment]
Uhm, you know that code more than me, I think.
And if we agree with the present contributing guide, we can add as a first version for now then update later.

**Pull request merged**
